github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
tasks:
  - before: ./scripts/gitpod-before.sh
  # Init should work now
  - init: source ./scripts/gitpod-env.sh && pnpm install
    command: docker compose up db db2 cache -d && pnpm dev

# security issues, unauthorised commits to our repository
image: nberlette/gitpod-enhanced:latest
vscode:
  extensions:
    - bradlc.vscode-tailwindcss
    - davidanson.vscode-markdownlint
    - mikestead.dotenv
    - Prisma.prisma
    - rvest.vs-code-prettier-eslint
    - ms-azuretools.vscode-docker
    - dbaeumer.vscode-eslint
    - prantlf.fold-on-open
    - aaron-bond.better-comments
    - vivaxy.vscode-conventional-commits
    - christian-kohler.path-intellisense
    - christian-kohler.npm-intellisense
    - sndst00m.markdown-github-dark-pack
    - cschleiden.vscode-github-actions
    - rangav.vscode-thunder-client
    - DigitalBrainstem.javascript-ejs-support
    - code-thunder-client
    - DigitalBrainstem.javascript-ejs-support
